AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      Handler: blank-csharp::blankCsharp.Function::FunctionHandler
      Runtime: dotnet6
      CodeUri: src/blank-csharp/bin/Release/net6.0/blank-csharp.zip
      Description: Call the AWS Lambda API
      MemorySize: 256
      Timeout: 9
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers: [
        arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:29,
        arn:aws:lambda:us-east-1:464622532012:layer:dd-trace-dotnet:6
      ]
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
          DD_SITE: datadoghq.com
          DD_API_KEY: <API_KEY>
          DD_VERSION: 0.0.1
          DD_ENV: dev
          DD_SERVICE: net6-test
          DD_APM_ENABLED: true
          DD_TRACE_ENABLED: true
          DD_LOGS_INJECTION: false
          DD_SERVERLESS_LOGS_ENABLED: false
          DD_CAPTURE_LAMBDA_PAYLOAD: true

